//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T2.CLS.LogTransport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T2.CLS.LogTransport.Properties.Logs", typeof(Logs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {propertyName} ignored.
        /// </summary>
        internal static string CLT00001 {
            get {
                return ResourceManager.GetString("CLT00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending log in ClickHouse: {content}.
        /// </summary>
        internal static string CLT00002 {
            get {
                return ResourceManager.GetString("CLT00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Output plugin. Type &apos;{pluginName}&apos;. SystemName &apos;{systemName}&apos;.
        /// </summary>
        internal static string CLT00003 {
            get {
                return ResourceManager.GetString("CLT00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogController created.
        /// </summary>
        internal static string SLT00001 {
            get {
                return ResourceManager.GetString("SLT00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~LogController End.
        /// </summary>
        internal static string SLT00002 {
            get {
                return ResourceManager.GetString("SLT00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~LogController Start.
        /// </summary>
        internal static string SLT00003 {
            get {
                return ResourceManager.GetString("SLT00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Metrics() =&gt;{metricData}.
        /// </summary>
        internal static string SLT00004 {
            get {
                return ResourceManager.GetString("SLT00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log from system: {system}.
        /// </summary>
        internal static string SLT00005 {
            get {
                return ResourceManager.GetString("SLT00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not save log for system &apos;{CLS}&apos;.
        /// </summary>
        internal static string SLT00006 {
            get {
                return ResourceManager.GetString("SLT00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input line: {line}.
        /// </summary>
        internal static string SLT00007 {
            get {
                return ResourceManager.GetString("SLT00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~LogMetrics Start.
        /// </summary>
        internal static string SLT00008 {
            get {
                return ResourceManager.GetString("SLT00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~LogMetrics End.
        /// </summary>
        internal static string SLT00009 {
            get {
                return ResourceManager.GetString("SLT00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~PluginFactory Start.
        /// </summary>
        internal static string SLT00010 {
            get {
                return ResourceManager.GetString("SLT00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~PluginFactory End.
        /// </summary>
        internal static string SLT00011 {
            get {
                return ResourceManager.GetString("SLT00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~PluginFactory.
        /// </summary>
        internal static string SLT00012 {
            get {
                return ResourceManager.GetString("SLT00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Output {pluginType} plugin. SystemName: {systemName}.
        /// </summary>
        internal static string SLT00013 {
            get {
                return ResourceManager.GetString("SLT00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin not created..
        /// </summary>
        internal static string SLT00014 {
            get {
                return ResourceManager.GetString("SLT00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main buffer settings config: {bufferSettingsConfig}.
        /// </summary>
        internal static string SLT00019 {
            get {
                return ResourceManager.GetString("SLT00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child settings empty. Parent config is applied..
        /// </summary>
        internal static string SLT00020 {
            get {
                return ResourceManager.GetString("SLT00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child and parent settings merged..
        /// </summary>
        internal static string SLT00021 {
            get {
                return ResourceManager.GetString("SLT00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin output config: {clickHousePluginConfig}.
        /// </summary>
        internal static string SLT00022 {
            get {
                return ResourceManager.GetString("SLT00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin output config: {forwardOutputConfig}.
        /// </summary>
        internal static string SLT00023 {
            get {
                return ResourceManager.GetString("SLT00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child settings empty. Parent config is applied..
        /// </summary>
        internal static string SLT00024 {
            get {
                return ResourceManager.GetString("SLT00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child and parent settings merged..
        /// </summary>
        internal static string SLT00025 {
            get {
                return ResourceManager.GetString("SLT00025", resourceCulture);
            }
        }
    }
}
